### ISSUE TITLE
Optimize main composite creation

### ISSUE THREAD

**Issue by cstockloew** [universAAL/maven#1]
Now that we have optimized the creation of test-composites (see universAAL/platform#9), there may be a possibility to optimize the creation of the main composite as well. 

Most of the bundles in a composite are from the mw. However, the mw has its own composite already and it is possible to have a composite inside another composite. Thus, the collection of transitive dependencies can be stopped as soon as a bundle from the mw is detected. Only the detected bundle version needs to be stored. Then, when the composite is written, the first line would be something like:
`scan-composite:mvn:org.universAAL.middleware/mw.composite/VERSION/composite`
(with the found version).

This would apply only to bundles that are not part of the mw. Maybe we could do something for mw bundles as well, and maybe we could completely disable them, as we only need the mw.composite for run configs.

The uaal-maven-plugin needs to be adapted for this. I would need to make some tests to see if this is working correctly.

**Comment by amedranogil** [comment]
this was the original idea I discussed with Marek (the developer for this plugin). I don't quite remember the conversation now as to why the decision was what it was.
It would be a matter of analyzing the code to see if this wasn't done because it was impractical, or other reasons.

**Comment by cstockloew** [comment]
it may have something to do with pax runner. I noticed a problem for a pax runner profile, a composite which had only one entry for scan-composite. I changed it to the nested composite and it worked. I will check.

**Comment by cstockloew** [comment]
FYI:

I just made a test.

You can provide your own artifact.composite file by placing it into the base folder (where the pom file is located). I did that for ont.composite, modified it by removing all mw bundles and replacing them with the one mw-composite entry. I mvn-installed it.

I then created a new RunConfig with only one entry:
scan-composite:mvn:org.universAAL.ontology/ont.composite/3.4.1-SNAPSHOT/composite
and it worked correctly. I also checked the cache folder, and the composites are correct: the modified ont.composite and the mw.composite...

So, Pax Runner in Eclipse seems not to be a problem (at least not anymore). But there is also the pax runner used in itests. Maybe that's the problem. But this is using the test-composite.

I did the very same thing shortly for optimizing the uAAL Pax Tab: all mw bundles are now skipped (mw version is selected by a drop-down menu). It works, but it was a hell of a lot work to find out how to realize the skipping. It uses Eclipse aether for resolving the dependencies and this is poorly(!) documented. Took me quite a while to find out the exact spot...

I will go on trying to modify uaal-maven-plugin....

**Comment by cstockloew** [comment]
OK, the result:

itests seems not to download any bundles, it only uses the ones in the local repo. The itests-composite generation ensures that all bundles are downloaded. Therefore it was not changed, it will traverse all transitive dependencies.

The main composite generation is now modified:
- if the bundle is from mw (groupID = org.universAAL.middleware) then there is no change
- if the bundle is from another repo then the traversal stops when it finds a bundle from mw (but not karaf.feature, see below). The resulting main-composite includes the nested mw-composite.

There was one catch: the main-composite generation also creates the list of versions of all artifacts (file artifacts.versions). This list is used in the creation of karaf-features. But, AFAIK, the only mw component that is used in the karaf.features of other repos is mw.karaf.feature. Therefore, the main-composite generation includes mw.karaf.feature in the traversal (and, thus, it appears also in artifacts.versions).

This can be turned off by calling -DuseMwComposite=false. Then, the nested mw-composite is not used and all transitive dependencies for the main composite are traversed as before.

I made a test for ont repo and the time saved was ~ 4,47s per project, which will save us ~ 20 min for all uaal bundles.

I also tested pax runner with these changes and there is no problem, the nested composite works.

Please check everything, especially that karaf still works. I have pushed the changes, but they are not yet deployed.

**Comment by cstockloew** [comment]
no problem so far, I'm closing this item..
