### ISSUE TITLE
Skip composite creation for karaf.features

### ISSUE THREAD

**Issue by cstockloew** [universAAL/maven#2]
This takes especially long, since it typically contains many (if not all) bundls from (dependent) repos, and a composite for a karaf.feature does not makes sense.

**Comment by amedranogil** [comment]
BUT, the problem is that the version of the dependant repos is used for the feature filtering (adding the correct version to the feature). This version file is created during the composite generation.

**Comment by cstockloew** [comment]
right, I completely forgot.

Closing this item

**Comment by amedranogil** [comment]
we could deactivate, but we lost the version tracking in the poms (it would be done via a global variable).
or we could look for an alternative to build the versions intermediate file, instead of through the composite.
